### PR TITLE
Logging #2

### LINKED ISSUE #55: Backend Logging System
Add some sort of logging mechanism to GroundStation's backend, possibly as a log file. This should ideally be available on the frontend to view.

### PR DESCRIPTION
**Pull request by krishnans2006**
View logs route + Minor logging changes

Still resolves #55 

Needs frontend support to populate `Console + Error Messages` box using `/logs` route: @pizzalemon

### CODE REVIEW

**Comment by krishnans2006** [comment]
@pizzalemon backend support for this is complete, you can start working on frontend support at any time. No more commits will be made on this branch by me.

**Comment by pizzalemon** [comment]
It'll probably take me a while lol.

**Comment by krishnans2006** [comment]
This PR should be continued **after** #68

**Comment by krishnans2006** [comment]
Will be implemented in #68

**Pull request closed without merging**
