### PR TITLE
Added Interop Server Connection at Server Initialization

### PR DESCRIPTION
**Pull request by krishnans2006**
Commented and Uncommented parts of code so that a connection to the Interop Server is made when the server runs.

### CODE REVIEW

**Comment by pizzalemon** [comment]
You should add `app.run(port=5000)` to the main method so the server actually runs.

**Comment by pizzalemon** [comment]
Could you squash the last three commits, to get rid of the two merges, too? While you're at it, perhaps you could get rid of `/hello` entirely and just have it be `/`, though that's up to you. Otherwise it looks good.

**Comment by krishnans2006** [comment]
@pizzalemon should be good to go now - I've forcefully squashed the three commits into one, although it did combine into your most recent update.

**Comment by pizzalemon** [comment]
> although it did combine into your most recent update.

(╯°□°）╯︵ ┻━┻

Ok looks good. You should merge now.

**Pull request merged**
