### PR TITLE
Add Proto File Translations

### PR DESCRIPTION
**Pull request by pizzalemon**
When the auvsi_suas library was added in a previous commit, the .proto file Python translations were not added. This commit adds them.

### CODE REVIEW

**Review by krishnans2006 — COMMENTED** [review]
I don't see the actual configuration file changes in this PR - the old one was closed, right? Shouldn't it be here too?

**Comment by pizzalemon** [comment]
https://developers.google.com/protocol-buffers/docs/pythontutorial .proto files are a way to define message formats. In the Interop repository this was pulled from, they use a .gitignore to remove any Python translations of this because it's redundant with the .proto file, but it was ignored by Git in our repository where we actually needed it. If you take a clean copy of the branch you'll notice that the backend can't run because it needs the translated files, which I have added in this PR.

**Comment by krishnans2006** [comment]
Yep I understand that. However, in #25, there was a configuration file error to be fixed, which was closed because of the lack of proto files. This PR includes the proto files, but I don't see the configuration file in the list of Files Changed. #25 was closed, so the config file changes weren't added to the upstream repository yet, right? I believe those changes are not included in this commit and PR.

**Comment by pizzalemon** [comment]
Oh, sorry about that. I'll open a separate PR for that. If you could, merge this PR for me if you think it's good.

> which [#25] was closed because of the lack of proto files

I want to note it was actually because I deleted the branch the PR was merging from for other reasons, not because of this problem.

**Review by krishnans2006 — APPROVED** [review]
Yep, the proto files are in and it's all correct.

**Pull request merged**
