### PR TITLE
ODLC submissions

### PR DESCRIPTION
**Pull request by krishnans2006**
**DO NOT MERGE**
Added support for adding, submitting, rejecting, and querying possible ODLC submissions.

**Ideal flow:**
 - Completed:
    - CV uploads images to `/server/assets/odlc_images/`.
    - JSON data is sent to server via POST: `/interop/odlc/add`.
    - ODLC Data in "queue" can be queried using `/interop/odlc/list` and `/interop/odlc/filter`, for display.
    - ODLC objects can be rejected or approved using the `/interop/odlc/submit` and `/interop/odlc/reject` routes.
    - Submitted objects are successfully sent to the interop server.
    - Rejected objects are marked as rejected, but can be submitted if deemed correct.
    - All submitted and rejected objects, along with non-reviewed objects, are kept in the "queue" of objects, so they can still be filtered.
 - To Do:
    - Saving objects in "queue" to a JSON file for safety, whenever the "queue" is changed.
    - Support for editing objects in the "queue" before submitting.
    - Possibility of editing submitted objects? Will likely not be included in this PR until further clarification.

### CODE REVIEW

**Comment by pizzalemon** [comment]
Hey, I'm assuming the new server methods only give the metadata of the image from CV, but not the actual image itself. How will the frontend be able to get that image data? It wouldn't be able to just grab them from `/server/assets/odlc_images/` because it'll be on multiple separate computers. I don't think it would be horrible if it just put it on the Flask server; images and videos are sent over the internet all the time, with speed. Also, what's the point of having it in a queue, rather than just in an array, or something?

**Comment by krishnans2006** [comment]
I see what you mean about the image itself - but my thought was this: The Groundstation will only be running on one PC, while CV operations can be split up into multiple PCs. So ideally, as long as the frontend and backend run on the same PC< they can access the images. However, your idea of sending images as separate API routes is probably a better idea.

Regarding the queue, the queue is basically just a list. The only reason I called it a queue is because the objects in the queue now have a "created time" and "to submit time", which is 5 minutes after the created time. Ideally, the objects will be auto-submitted when this time comes, so that it can be purely "autonomous". But anyway, the queue is basically just a list ordered by object times, which means it is the order of objects that will be auto-submitted.

**Comment by krishnans2006** [comment]
Will push final commits now.

Completed Flow:
 - CV uploads images to `/server/assets/odlc_images/`.
 - JSON data is sent to server via POST: `/interop/odlc/add`.
 - ODLC Data in "queue" can be queried using `/interop/odlc/list` and `/interop/odlc/filter`, for display.
 - ODLC objects can be rejected or approved using the `/interop/odlc/submit` and `/interop/odlc/reject` routes.
 - Submitted objects are successfully sent to the interop server.
 - Rejected objects are marked as rejected, but can be submitted if deemed correct.
 - All submitted and rejected objects, along with non-reviewed objects, are kept in the "queue" of objects, so they can still be filtered.
 - Queued objects are saved to a JSON file for safety, whenever the objects are told to save (not after every change, so that old saved JSON doesn't get overwrited).
 - Objects in the queue can be edited, but this will only apply local edits (not to the interop server).

Maybe:
 - Possibility of editing submitted objects? Will likely not be included in this PR until further clarification.

**Comment by pizzalemon** [comment]
Finally got to this lol. Why encode the image in Base64 in the image getter page? Also, why have an add to queue page? Off the top of my head, the only thing I can think of that would want to add to the queue would be the mav handler or CV, which wouldn't need that page. Also, as far as I can tell, the frontend wouldn't need that either.
That's my initial review on it. I want to clone it and test it on my own machine too.

**Comment by krishnans2006** [comment]
> Why encode the image in Base64 in the image getter page?

Because it's an easy way of sending image data via an API, and it can be decoded using React/JS.
> Also, why have an add to queue page? Off the top of my head, the only thing I can think of that would want to add to the queue would be the mav handler or CV, which wouldn't need that page.

Just in case. The CV Team mentioned that they might not have access to the Groundstation filesystem, so I wanted to let them use the route if need be (it's super simple to send a request in Python vs trying to save files/data manually in a completely different application.
> I want to clone it and test it on my own machine too.

Yes, go ahead! The API Testing Suite which I configured is shared with you on Postman. Use this [link](https://www.getpostman.com/collections/919dfe8a4b297e1b93ac).

**Comment by pizzalemon** [comment]
>Just in case. The CV Team mentioned...

Ah ok. I figured that our backend would be the one calling some sort of CV script through pure Python that would return something. Personally, I would omit it since we don't know how that will work yet, and we can then just take it as it comes.

I'll get to testing it out soon. I might not be able to tonight. I'd like to do that for any PR which isn't a small fix or change.

**Comment by pizzalemon** [comment]
I checked out the base64 thing and I didn't know that UTF-8 couldn't decode some of that stuff, so that seems fine. Anyways I didn't really check it very much. I think I'll start writing tests or something. I don't know.

You can merge it in.

**Comment by krishnans2006** [comment]
Alright - could you approve the PR first, though? It makes the entire process more streamlined.

**Review by pizzalemon — APPROVED** [review]
Approved.

**Pull request merged**
